// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4exp_cf_fixed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4exp_exp_joint_hiercf_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4exp_exp_joint_hiercfTx_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4exp_gompertz_joint_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4exp_relative_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4exp_weibull_joint_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gengamma_gengamma_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gompertz_gompertz_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gompertz_gompertzTx_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4gompertz_gompertz_joint_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lifetable_adjust_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4loglogistic_loglogistic_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lognormal_lognormal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4lognormal_relative_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4postpred_exp_exp_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4postpred_gqs_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4surv_joint_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibull_cf_fixed_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibull_relative_mix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibull_weibull_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4weibull_weibull_joint_mix_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4exp_cf_fixed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4exp_cf_fixed_mod, 0},
    {"_rcpp_module_boot_stan_fit4exp_exp_joint_hiercf_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4exp_exp_joint_hiercf_mod, 0},
    {"_rcpp_module_boot_stan_fit4exp_exp_joint_hiercfTx_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4exp_exp_joint_hiercfTx_mod, 0},
    {"_rcpp_module_boot_stan_fit4exp_gompertz_joint_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4exp_gompertz_joint_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4exp_relative_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4exp_relative_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4exp_weibull_joint_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4exp_weibull_joint_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4gengamma_gengamma_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gengamma_gengamma_mod, 0},
    {"_rcpp_module_boot_stan_fit4gompertz_gompertz_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gompertz_gompertz_mod, 0},
    {"_rcpp_module_boot_stan_fit4gompertz_gompertzTx_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gompertz_gompertzTx_mod, 0},
    {"_rcpp_module_boot_stan_fit4gompertz_gompertz_joint_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4gompertz_gompertz_joint_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4lifetable_adjust_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lifetable_adjust_mod, 0},
    {"_rcpp_module_boot_stan_fit4loglogistic_loglogistic_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4loglogistic_loglogistic_mod, 0},
    {"_rcpp_module_boot_stan_fit4lognormal_lognormal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lognormal_lognormal_mod, 0},
    {"_rcpp_module_boot_stan_fit4lognormal_relative_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4lognormal_relative_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4postpred_exp_exp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4postpred_exp_exp_mod, 0},
    {"_rcpp_module_boot_stan_fit4postpred_gqs_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4postpred_gqs_mod, 0},
    {"_rcpp_module_boot_stan_fit4surv_joint_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4surv_joint_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibull_cf_fixed_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibull_cf_fixed_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibull_relative_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibull_relative_mix_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibull_weibull_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibull_weibull_mod, 0},
    {"_rcpp_module_boot_stan_fit4weibull_weibull_joint_mix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4weibull_weibull_joint_mix_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rstanbmcm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
