// Generated by rstantools.  Do not edit by hand.

/*
    rstanbmcm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rstanbmcm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rstanbmcm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_postpred_gqs_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_postpred_gqs");
    reader.add_event(88, 86, "end", "model_postpred_gqs");
    return reader;
}
template <typename T0__, typename T1__, typename T2__, class RNG>
std::vector<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type>
rate_mean_rng(const T0__& curefrac,
                  const T1__& lambda0,
                  const T2__& lambda_bg,
                  const int& n, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 11;
        validate_non_negative_index("lambda", "n", n);
        std::vector<local_scalar_t__  > lambda(n, local_scalar_t__(DUMMY_VAR__));
        stan::math::initialize(lambda, DUMMY_VAR__);
        stan::math::fill(lambda, DUMMY_VAR__);
        current_statement_begin__ = 12;
        validate_non_negative_index("cf", "n", n);
        std::vector<local_scalar_t__  > cf(n, local_scalar_t__(DUMMY_VAR__));
        stan::math::initialize(cf, DUMMY_VAR__);
        stan::math::fill(cf, DUMMY_VAR__);
        current_statement_begin__ = 14;
        for (int i = 1; i <= n; ++i) {
            current_statement_begin__ = 15;
            stan::model::assign(cf, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                        uniform_rng(0, 1, base_rng__), 
                        "assigning variable cf");
            current_statement_begin__ = 17;
            if (as_bool(logical_lt(get_base1(cf, i, "cf", 1), curefrac))) {
                current_statement_begin__ = 18;
                stan::model::assign(lambda, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            lambda_bg, 
                            "assigning variable lambda");
            } else {
                current_statement_begin__ = 20;
                stan::model::assign(lambda, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (lambda_bg + lambda0), 
                            "assigning variable lambda");
            }
        }
        current_statement_begin__ = 23;
        return stan::math::promote_scalar<fun_return_scalar_t__>(lambda);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct rate_mean_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, class RNG>
        std::vector<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type>
    operator()(const T0__& curefrac,
                  const T1__& lambda0,
                  const T2__& lambda_bg,
                  const int& n, RNG& base_rng__, std::ostream* pstream__) const {
        return rate_mean_rng(curefrac, lambda0, lambda_bg, n, base_rng__, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, class RNG>
std::vector<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type>
rate_casemix_rng(const T0__& curefrac,
                     const std::vector<T1__>& lambda0,
                     const std::vector<T2__>& lambda_bg, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 28;
        int n(0);
        (void) n;  // dummy to suppress unused var warning
        stan::math::fill(n, std::numeric_limits<int>::min());
        stan::math::assign(n,num_elements(lambda0));
        current_statement_begin__ = 29;
        validate_non_negative_index("lambda", "n", n);
        std::vector<local_scalar_t__  > lambda(n, local_scalar_t__(DUMMY_VAR__));
        stan::math::initialize(lambda, DUMMY_VAR__);
        stan::math::fill(lambda, DUMMY_VAR__);
        current_statement_begin__ = 30;
        validate_non_negative_index("cf", "n", n);
        std::vector<local_scalar_t__  > cf(n, local_scalar_t__(DUMMY_VAR__));
        stan::math::initialize(cf, DUMMY_VAR__);
        stan::math::fill(cf, DUMMY_VAR__);
        current_statement_begin__ = 32;
        for (int i = 1; i <= n; ++i) {
            current_statement_begin__ = 33;
            stan::model::assign(cf, 
                        stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                        uniform_rng(0, 1, base_rng__), 
                        "assigning variable cf");
            current_statement_begin__ = 35;
            if (as_bool(logical_lt(get_base1(cf, i, "cf", 1), curefrac))) {
                current_statement_begin__ = 36;
                stan::model::assign(lambda, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            get_base1(lambda_bg, i, "lambda_bg", 1), 
                            "assigning variable lambda");
            } else {
                current_statement_begin__ = 38;
                stan::model::assign(lambda, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (get_base1(lambda_bg, i, "lambda_bg", 1) + get_base1(lambda0, i, "lambda0", 1)), 
                            "assigning variable lambda");
            }
        }
        current_statement_begin__ = 41;
        return stan::math::promote_scalar<fun_return_scalar_t__>(lambda);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct rate_casemix_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, class RNG>
        std::vector<typename boost::math::tools::promote_args<T0__, T1__, T2__>::type>
    operator()(const T0__& curefrac,
                     const std::vector<T1__>& lambda0,
                     const std::vector<T2__>& lambda_bg, RNG& base_rng__, std::ostream* pstream__) const {
        return rate_casemix_rng(curefrac, lambda0, lambda_bg, base_rng__, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_postpred_gqs
  : public stan::model::model_base_crtp<model_postpred_gqs> {
private:
        int n;
        double os_model;
        double pfs_model;
public:
    model_postpred_gqs(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_postpred_gqs(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_postpred_gqs_namespace::model_postpred_gqs";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 47;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 1);
            current_statement_begin__ = 49;
            context__.validate_dims("data initialization", "os_model", "double", context__.to_vec());
            os_model = double(0);
            vals_r__ = context__.vals_r("os_model");
            pos__ = 0;
            os_model = vals_r__[pos__++];
            check_greater_or_equal(function__, "os_model", os_model, 1);
            current_statement_begin__ = 50;
            context__.validate_dims("data initialization", "pfs_model", "double", context__.to_vec());
            pfs_model = double(0);
            vals_r__ = context__.vals_r("pfs_model");
            pos__ = 0;
            pfs_model = vals_r__[pos__++];
            check_greater_or_equal(function__, "pfs_model", pfs_model, 1);
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 54;
            num_params_r__ += 1;
            current_statement_begin__ = 55;
            num_params_r__ += 1;
            current_statement_begin__ = 57;
            validate_non_negative_index("lambda_os", "(logical_eq(os_model, 1) ? n : 0 )", (logical_eq(os_model, 1) ? n : 0 ));
            num_params_r__ += (1 * (logical_eq(os_model, 1) ? n : 0 ));
            current_statement_begin__ = 58;
            validate_non_negative_index("lambda_pfs", "(logical_eq(pfs_model, 1) ? n : 0 )", (logical_eq(pfs_model, 1) ? n : 0 ));
            num_params_r__ += (1 * (logical_eq(pfs_model, 1) ? n : 0 ));
            current_statement_begin__ = 59;
            validate_non_negative_index("lambda_os_bg", "n", n);
            num_params_r__ += (1 * n);
            current_statement_begin__ = 60;
            validate_non_negative_index("lambda_pfs_bg", "n", n);
            num_params_r__ += (1 * n);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_postpred_gqs() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 54;
        if (!(context__.contains_r("cf_os")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable cf_os missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("cf_os");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "cf_os", "double", context__.to_vec());
        double cf_os(0);
        cf_os = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, cf_os);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable cf_os: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 55;
        if (!(context__.contains_r("cf_pfs")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable cf_pfs missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("cf_pfs");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "cf_pfs", "double", context__.to_vec());
        double cf_pfs(0);
        cf_pfs = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1, cf_pfs);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable cf_pfs: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 57;
        if (!(context__.contains_r("lambda_os")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda_os missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda_os");
        pos__ = 0U;
        validate_non_negative_index("lambda_os", "(logical_eq(os_model, 1) ? n : 0 )", (logical_eq(os_model, 1) ? n : 0 ));
        context__.validate_dims("parameter initialization", "lambda_os", "double", context__.to_vec((logical_eq(os_model, 1) ? n : 0 )));
        std::vector<double> lambda_os((logical_eq(os_model, 1) ? n : 0 ), double(0));
        size_t lambda_os_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_os_k_0_max__; ++k_0__) {
            lambda_os[k_0__] = vals_r__[pos__++];
        }
        size_t lambda_os_i_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t i_0__ = 0; i_0__ < lambda_os_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, lambda_os[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda_os: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 58;
        if (!(context__.contains_r("lambda_pfs")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda_pfs missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda_pfs");
        pos__ = 0U;
        validate_non_negative_index("lambda_pfs", "(logical_eq(pfs_model, 1) ? n : 0 )", (logical_eq(pfs_model, 1) ? n : 0 ));
        context__.validate_dims("parameter initialization", "lambda_pfs", "double", context__.to_vec((logical_eq(pfs_model, 1) ? n : 0 )));
        std::vector<double> lambda_pfs((logical_eq(pfs_model, 1) ? n : 0 ), double(0));
        size_t lambda_pfs_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_k_0_max__; ++k_0__) {
            lambda_pfs[k_0__] = vals_r__[pos__++];
        }
        size_t lambda_pfs_i_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t i_0__ = 0; i_0__ < lambda_pfs_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, lambda_pfs[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda_pfs: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 59;
        if (!(context__.contains_r("lambda_os_bg")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda_os_bg missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda_os_bg");
        pos__ = 0U;
        validate_non_negative_index("lambda_os_bg", "n", n);
        context__.validate_dims("parameter initialization", "lambda_os_bg", "double", context__.to_vec(n));
        std::vector<double> lambda_os_bg(n, double(0));
        size_t lambda_os_bg_k_0_max__ = n;
        for (size_t k_0__ = 0; k_0__ < lambda_os_bg_k_0_max__; ++k_0__) {
            lambda_os_bg[k_0__] = vals_r__[pos__++];
        }
        size_t lambda_os_bg_i_0_max__ = n;
        for (size_t i_0__ = 0; i_0__ < lambda_os_bg_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, lambda_os_bg[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda_os_bg: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 60;
        if (!(context__.contains_r("lambda_pfs_bg")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lambda_pfs_bg missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lambda_pfs_bg");
        pos__ = 0U;
        validate_non_negative_index("lambda_pfs_bg", "n", n);
        context__.validate_dims("parameter initialization", "lambda_pfs_bg", "double", context__.to_vec(n));
        std::vector<double> lambda_pfs_bg(n, double(0));
        size_t lambda_pfs_bg_k_0_max__ = n;
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_bg_k_0_max__; ++k_0__) {
            lambda_pfs_bg[k_0__] = vals_r__[pos__++];
        }
        size_t lambda_pfs_bg_i_0_max__ = n;
        for (size_t i_0__ = 0; i_0__ < lambda_pfs_bg_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, lambda_pfs_bg[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lambda_pfs_bg: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 54;
            local_scalar_t__ cf_os;
            (void) cf_os;  // dummy to suppress unused var warning
            if (jacobian__)
                cf_os = in__.scalar_lub_constrain(0, 1, lp__);
            else
                cf_os = in__.scalar_lub_constrain(0, 1);
            current_statement_begin__ = 55;
            local_scalar_t__ cf_pfs;
            (void) cf_pfs;  // dummy to suppress unused var warning
            if (jacobian__)
                cf_pfs = in__.scalar_lub_constrain(0, 1, lp__);
            else
                cf_pfs = in__.scalar_lub_constrain(0, 1);
            current_statement_begin__ = 57;
            std::vector<local_scalar_t__> lambda_os;
            size_t lambda_os_d_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
            lambda_os.reserve(lambda_os_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < lambda_os_d_0_max__; ++d_0__) {
                if (jacobian__)
                    lambda_os.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    lambda_os.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 58;
            std::vector<local_scalar_t__> lambda_pfs;
            size_t lambda_pfs_d_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
            lambda_pfs.reserve(lambda_pfs_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < lambda_pfs_d_0_max__; ++d_0__) {
                if (jacobian__)
                    lambda_pfs.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    lambda_pfs.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 59;
            std::vector<local_scalar_t__> lambda_os_bg;
            size_t lambda_os_bg_d_0_max__ = n;
            lambda_os_bg.reserve(lambda_os_bg_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < lambda_os_bg_d_0_max__; ++d_0__) {
                if (jacobian__)
                    lambda_os_bg.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    lambda_os_bg.push_back(in__.scalar_lb_constrain(0));
            }
            current_statement_begin__ = 60;
            std::vector<local_scalar_t__> lambda_pfs_bg;
            size_t lambda_pfs_bg_d_0_max__ = n;
            lambda_pfs_bg.reserve(lambda_pfs_bg_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < lambda_pfs_bg_d_0_max__; ++d_0__) {
                if (jacobian__)
                    lambda_pfs_bg.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    lambda_pfs_bg.push_back(in__.scalar_lb_constrain(0));
            }
            // model body
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("cf_os");
        names__.push_back("cf_pfs");
        names__.push_back("lambda_os");
        names__.push_back("lambda_pfs");
        names__.push_back("lambda_os_bg");
        names__.push_back("lambda_pfs_bg");
        names__.push_back("lambda_os_tilde");
        names__.push_back("t_os_tilde");
        names__.push_back("lambda_pfs_tilde");
        names__.push_back("t_pfs_tilde");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_eq(os_model, 1) ? n : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_eq(pfs_model, 1) ? n : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_eq(os_model, 1) ? n : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_eq(os_model, 1) ? n : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_eq(pfs_model, 1) ? n : 0 ));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((logical_eq(pfs_model, 1) ? n : 0 ));
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_postpred_gqs_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double cf_os = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(cf_os);
        double cf_pfs = in__.scalar_lub_constrain(0, 1);
        vars__.push_back(cf_pfs);
        std::vector<double> lambda_os;
        size_t lambda_os_d_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        lambda_os.reserve(lambda_os_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < lambda_os_d_0_max__; ++d_0__) {
            lambda_os.push_back(in__.scalar_lb_constrain(0));
        }
        size_t lambda_os_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_os_k_0_max__; ++k_0__) {
            vars__.push_back(lambda_os[k_0__]);
        }
        std::vector<double> lambda_pfs;
        size_t lambda_pfs_d_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        lambda_pfs.reserve(lambda_pfs_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < lambda_pfs_d_0_max__; ++d_0__) {
            lambda_pfs.push_back(in__.scalar_lb_constrain(0));
        }
        size_t lambda_pfs_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_k_0_max__; ++k_0__) {
            vars__.push_back(lambda_pfs[k_0__]);
        }
        std::vector<double> lambda_os_bg;
        size_t lambda_os_bg_d_0_max__ = n;
        lambda_os_bg.reserve(lambda_os_bg_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < lambda_os_bg_d_0_max__; ++d_0__) {
            lambda_os_bg.push_back(in__.scalar_lb_constrain(0));
        }
        size_t lambda_os_bg_k_0_max__ = n;
        for (size_t k_0__ = 0; k_0__ < lambda_os_bg_k_0_max__; ++k_0__) {
            vars__.push_back(lambda_os_bg[k_0__]);
        }
        std::vector<double> lambda_pfs_bg;
        size_t lambda_pfs_bg_d_0_max__ = n;
        lambda_pfs_bg.reserve(lambda_pfs_bg_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < lambda_pfs_bg_d_0_max__; ++d_0__) {
            lambda_pfs_bg.push_back(in__.scalar_lb_constrain(0));
        }
        size_t lambda_pfs_bg_k_0_max__ = n;
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_bg_k_0_max__; ++k_0__) {
            vars__.push_back(lambda_pfs_bg[k_0__]);
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 69;
            validate_non_negative_index("lambda_os_tilde", "(logical_eq(os_model, 1) ? n : 0 )", (logical_eq(os_model, 1) ? n : 0 ));
            std::vector<double> lambda_os_tilde((logical_eq(os_model, 1) ? n : 0 ), double(0));
            stan::math::initialize(lambda_os_tilde, DUMMY_VAR__);
            stan::math::fill(lambda_os_tilde, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("t_os_tilde", "(logical_eq(os_model, 1) ? n : 0 )", (logical_eq(os_model, 1) ? n : 0 ));
            std::vector<double> t_os_tilde((logical_eq(os_model, 1) ? n : 0 ), double(0));
            stan::math::initialize(t_os_tilde, DUMMY_VAR__);
            stan::math::fill(t_os_tilde, DUMMY_VAR__);
            current_statement_begin__ = 71;
            validate_non_negative_index("lambda_pfs_tilde", "(logical_eq(pfs_model, 1) ? n : 0 )", (logical_eq(pfs_model, 1) ? n : 0 ));
            std::vector<double> lambda_pfs_tilde((logical_eq(pfs_model, 1) ? n : 0 ), double(0));
            stan::math::initialize(lambda_pfs_tilde, DUMMY_VAR__);
            stan::math::fill(lambda_pfs_tilde, DUMMY_VAR__);
            current_statement_begin__ = 72;
            validate_non_negative_index("t_pfs_tilde", "(logical_eq(pfs_model, 1) ? n : 0 )", (logical_eq(pfs_model, 1) ? n : 0 ));
            std::vector<double> t_pfs_tilde((logical_eq(pfs_model, 1) ? n : 0 ), double(0));
            stan::math::initialize(t_pfs_tilde, DUMMY_VAR__);
            stan::math::fill(t_pfs_tilde, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 73;
            if (pstream__) {
                stan_print(pstream__,lambda_os_bg);
                *pstream__ << std::endl;
            }
            current_statement_begin__ = 75;
            if (as_bool(logical_eq(os_model, 1))) {
                current_statement_begin__ = 77;
                stan::math::assign(lambda_os_tilde, rate_casemix_rng(cf_os, lambda_os, lambda_os_bg, base_rng__, pstream__));
                current_statement_begin__ = 80;
                stan::math::assign(t_os_tilde, exponential_rng(lambda_os_tilde, base_rng__));
                current_statement_begin__ = 82;
                stan::math::assign(lambda_pfs_tilde, rate_casemix_rng(cf_pfs, lambda_pfs, lambda_pfs_bg, base_rng__, pstream__));
                current_statement_begin__ = 84;
                stan::math::assign(t_pfs_tilde, exponential_rng(lambda_pfs_tilde, base_rng__));
            }
            // validate, write generated quantities
            current_statement_begin__ = 69;
            size_t lambda_os_tilde_i_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
            for (size_t i_0__ = 0; i_0__ < lambda_os_tilde_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "lambda_os_tilde[i_0__]", lambda_os_tilde[i_0__], 0);
            }
            size_t lambda_os_tilde_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
            for (size_t k_0__ = 0; k_0__ < lambda_os_tilde_k_0_max__; ++k_0__) {
                vars__.push_back(lambda_os_tilde[k_0__]);
            }
            current_statement_begin__ = 70;
            size_t t_os_tilde_i_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
            for (size_t i_0__ = 0; i_0__ < t_os_tilde_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "t_os_tilde[i_0__]", t_os_tilde[i_0__], 0);
            }
            size_t t_os_tilde_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
            for (size_t k_0__ = 0; k_0__ < t_os_tilde_k_0_max__; ++k_0__) {
                vars__.push_back(t_os_tilde[k_0__]);
            }
            current_statement_begin__ = 71;
            size_t lambda_pfs_tilde_i_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
            for (size_t i_0__ = 0; i_0__ < lambda_pfs_tilde_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "lambda_pfs_tilde[i_0__]", lambda_pfs_tilde[i_0__], 0);
            }
            size_t lambda_pfs_tilde_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
            for (size_t k_0__ = 0; k_0__ < lambda_pfs_tilde_k_0_max__; ++k_0__) {
                vars__.push_back(lambda_pfs_tilde[k_0__]);
            }
            current_statement_begin__ = 72;
            size_t t_pfs_tilde_i_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
            for (size_t i_0__ = 0; i_0__ < t_pfs_tilde_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "t_pfs_tilde[i_0__]", t_pfs_tilde[i_0__], 0);
            }
            size_t t_pfs_tilde_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
            for (size_t k_0__ = 0; k_0__ < t_pfs_tilde_k_0_max__; ++k_0__) {
                vars__.push_back(t_pfs_tilde[k_0__]);
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_postpred_gqs";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "cf_os";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "cf_pfs";
        param_names__.push_back(param_name_stream__.str());
        size_t lambda_os_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_os_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_os" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_pfs_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_pfs" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_os_bg_k_0_max__ = n;
        for (size_t k_0__ = 0; k_0__ < lambda_os_bg_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_os_bg" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_pfs_bg_k_0_max__ = n;
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_bg_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_pfs_bg" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        size_t lambda_os_tilde_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_os_tilde_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_os_tilde" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t t_os_tilde_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < t_os_tilde_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "t_os_tilde" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_pfs_tilde_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_tilde_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_pfs_tilde" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t t_pfs_tilde_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < t_pfs_tilde_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "t_pfs_tilde" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "cf_os";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "cf_pfs";
        param_names__.push_back(param_name_stream__.str());
        size_t lambda_os_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_os_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_os" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_pfs_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_pfs" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_os_bg_k_0_max__ = n;
        for (size_t k_0__ = 0; k_0__ < lambda_os_bg_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_os_bg" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_pfs_bg_k_0_max__ = n;
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_bg_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_pfs_bg" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        size_t lambda_os_tilde_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_os_tilde_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_os_tilde" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t t_os_tilde_k_0_max__ = (logical_eq(os_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < t_os_tilde_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "t_os_tilde" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lambda_pfs_tilde_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < lambda_pfs_tilde_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lambda_pfs_tilde" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t t_pfs_tilde_k_0_max__ = (logical_eq(pfs_model, 1) ? n : 0 );
        for (size_t k_0__ = 0; k_0__ < t_pfs_tilde_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "t_pfs_tilde" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_postpred_gqs_namespace::model_postpred_gqs stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
