# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("exp_exp_joint_hiercf", "exp_exp_joint_hiercfTx", "exp_lognormalTx", "gengamma_gengamma", "gompertz_gompertz", "gompertz_gompertzTx", "lifetable_adjust", "loglogistic_loglogistic", "lognormal_lognormal", "postpred_exp_exp", "postpred_exp_expTx", "postpred_gqs", "postpred_weibull_weibullTx", "weibull_weibull")

# load each stan module
Rcpp::loadModule("stan_fit4exp_exp_joint_hiercf_mod", what = TRUE)
Rcpp::loadModule("stan_fit4exp_exp_joint_hiercfTx_mod", what = TRUE)
Rcpp::loadModule("stan_fit4exp_lognormalTx_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gengamma_gengamma_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gompertz_gompertz_mod", what = TRUE)
Rcpp::loadModule("stan_fit4gompertz_gompertzTx_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lifetable_adjust_mod", what = TRUE)
Rcpp::loadModule("stan_fit4loglogistic_loglogistic_mod", what = TRUE)
Rcpp::loadModule("stan_fit4lognormal_lognormal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4postpred_exp_exp_mod", what = TRUE)
Rcpp::loadModule("stan_fit4postpred_exp_expTx_mod", what = TRUE)
Rcpp::loadModule("stan_fit4postpred_gqs_mod", what = TRUE)
Rcpp::loadModule("stan_fit4postpred_weibull_weibullTx_mod", what = TRUE)
Rcpp::loadModule("stan_fit4weibull_weibull_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
